# Generated by Django 2.1.5 on 2022-01-21 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre de la Categoria')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_empresa', to='core.Categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Nivel de Escalacion',
                'verbose_name_plural': 'Niveles de Escalación',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Nivel de Escalacion',
                'verbose_name_plural': 'Niveles de Escalación',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='TablaEscalacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre')),
                ('last_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Apellido')),
                ('mail', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Correo')),
                ('phone', models.IntegerField(blank=True, max_length=200, null=True, verbose_name='Teléfono')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_empresa', to='core.Empresa', verbose_name='Empresa')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_empresa', to='core.Nivel', verbose_name='Nivel de Escalación o Cargo')),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Sliders',
                'ordering': ['-created'],
            },
        ),
    ]
