# Generated by Django 2.1.5 on 2022-01-21 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablaescalacion',
            name='phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Teléfono'),
        ),
    ]
