# Generated by Django 2.1.5 on 2022-01-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220121_0845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tablaescalacion',
            options={'ordering': ['order'], 'verbose_name': 'Tabla de Escalación', 'verbose_name_plural': 'Tablas de Escalaciones'},
        ),
        migrations.AlterField(
            model_name='tablaescalacion',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Orden'),
        ),
    ]
