# Generated by Django 2.1.5 on 2022-01-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220121_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablaescalacion',
            name='excel',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='', verbose_name='Adjunta Archivo Excel'),
        ),
    ]
