# Generated by Django 2.1.5 on 2022-01-25 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tablaescalacion_excel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablaescalacion',
            name='excel',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='documents', verbose_name='Adjunta Archivo Excel'),
        ),
    ]
